[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "dist" # not strictly necessary for an API, but good practice

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "serverless"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
