export type KomikType = "manga" | "manhwa" | "manhua";
export type GenreType =
  | "academy"
  | "action"
  | "adaptation"
  | "adult"
  | "adventure"
  | "apocalypse"
  | "beasts"
  | "blacksmith"
  | "comedy"
  | "comic"
  | "cooking"
  | "crime"
  | "crossdressing"
  | "dark-fantasy"
  | "demon"
  | "demons"
  | "doujinshi"
  | "drama"
  | "ecchi"
  | "entertainment"
  | "fantasy"
  | "game"
  | "gender-bender"
  | "genderswap"
  | "genius"
  | "ghosts"
  | "gore"
  | "gyaru"
  | "harem"
  | "hentai"
  | "historical"
  | "horror"
  | "isekai"
  | "josei"
  | "knight"
  | "long-strip"
  | "magic"
  | "magical-girls"
  | "manga"
  | "mangatoon"
  | "manhwa"
  | "martial-art"
  | "martial-arts"
  | "mature"
  | "mc-rebirth"
  | "mecha"
  | "medical"
  | "military"
  | "monster"
  | "monster-girls"
  | "monsters"
  | "murim"
  | "music"
  | "mystery"
  | "office-workers"
  | "one-shot"
  | "oneshot"
  | "police"
  | "psychological"
  | "regression"
  | "reincarnation"
  | "revenge"
  | "romance"
  | "school"
  | "school-life"
  | "sci-fi"
  | "seinen"
  | "sexual-violence"
  | "shotacon"
  | "shoujo"
  | "shoujo-ai"
  | "shoujog"
  | "shounen"
  | "shounen-ai"
  | "slice-of-life"
  | "slow-life"
  | "smut"
  | "sport"
  | "sports"
  | "strategy"
  | "super-power"
  | "supernatural"
  | "survival"
  | "sword-fight"
  | "sword-master"
  | "swormanship"
  | "system"
  | "thriller"
  | "time-travel"
  | "tragedy"
  | "trauma"
  | "vampire"
  | "video-games"
  | "villainess"
  | "violence"
  | "web-comic"
  | "webtoon"
  | "webtoons"
  | "xianxia"
  | "xuanhuan"
  | "yuri";

export type ApiResponse<T> = {
  data: T;
};

export type BaseChapter = {
  title: string;
  slug: string;
};

export type BaseComic = {
  title: string;
  slug: string;
  thumbnail: string;
};
